
FROM node:alpine


WORKDIR '/app'
#WORKDIR '/app'
COPY  package.json .

RUN npm install
RUN npm cache clean --force

# RUN npm config set unsafe-perm true

COPY   . .
USER root
# ENV BABEL_DISABLE_CACHE 1
RUN chown -R node:node node_modules
RUN ls -l
USER node

CMD ["npm", "run","start"]